version: '3.1'
services:
    jenkins:
        build: master
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - /var/jenkins_home:/var/jenkins_home



    jenkins-slave:
        build: slave
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins
    
    jenkins-slave1:
        build: slave
        container_name: jenkins-slave1
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins
